version: "3"
services:
  nodestatus:
    image: cokemine/nodestatus
    container_name: nodestatus
    restart: always

    environment:
      PORT: 35601
      VERBOSE: "false"
      PING_INTERVAL: 30
      TZ: Asia/Shanghai

      USE_PUSH: "true"
      USE_IPC: "true"
      USE_WEB: "true"

      WEB_THEME: "hotaru-theme"
      WEB_TITLE: "Server Status"
      WEB_SUBTITLE: "Servers' Probes Set up with NodeStatus"
      WEB_HEADTITLE: "NodeStatus"

      WEB_USERNAME: "admin"
      WEB_PASSWORD: ""
      WEB_SECRET: ""

      PUSH_TIMEOUT: 120
      PUSH_DELAY: 15

      TGBOT_TOKEN: ""
      TGBOT_CHATID: ""
      TGBOT_PROXY: ""
      TGBOT_WEBHOOK: ""

    volumes:
      - /usr/local/NodeStatus/server:/usr/local/NodeStatus/server
      - /tmp:/tmp:rw

    ports:
      - "35601:35601"
