name: Docker Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Check Version
        id: checkver
        run: |
          cd "packages/nodestatus-server"
          version="v$(npm -s run env echo '$npm_package_version')"
          echo "::set-output name=version::${version}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build dockerfile
        uses: nick-invision/retry@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VERSION: ${{ steps.checkver.outputs.version }}
        with:
          timeout_minutes: 120
          max_attempts: 3
          # https://github.com/prisma/prisma/issues/5379
          command: |
            docker buildx build \
            --platform=linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/nodestatus:latest \
            --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/nodestatus:${VERSION}
